[package]
name = "slippi_analyzer"
version = "0.1.0"
edition = "2024"

[lib]
name="slippi_analyzer"
crate-type = ["cdylib"]

[dependencies]
slp_parser = { git = "https://github.com/AlexanderHarrison/slp_parser" }
tm_replay = { git = "https://github.com/AlexanderHarrison/tm_replay" }